### ISSUE TITLE
这个界面为什么没有关闭按钮？

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/hcashd#10]
Mac版

创建恢复钱包界面，为什么没有关闭按钮？
<img width="776" alt="2017-12-19 2 22 25" src="https://user-images.githubusercontent.com/949848/34143542-23aa7a12-e4c8-11e7-94d8-25ae0b4ae418.png">

**Comment by chaoguodeng** [comment]
@chengxulvtu 感谢提出这个问题，我们后续修复
