### ISSUE TITLE
设置钱包密码相关问题

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/hcashd#11]
<img width="771" alt="2017-12-19 2 25 02" src="https://user-images.githubusercontent.com/949848/34143603-79bdef92-e4c8-11e7-8538-dc331a360249.png">

1. 焦点在 ”钱包密码“ 框的时候，按”Tab"键，不能切换到“密码确认”文本框中。

**Comment by chaoguodeng** [comment]
@chengxulvtu 感谢建议
