### ISSUE TITLE
挖矿奖励已确认，可用余额为什么是0？

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/hcashd#14]
<img width="612" alt="2017-12-19 5 50 50" src="https://user-images.githubusercontent.com/949848/34151104-46d07d4e-e4e5-11e7-8dfe-3b8241722d00.png">

<img width="613" alt="2017-12-19 5 46 03" src="https://user-images.githubusercontent.com/949848/34151038-148f7736-e4e5-11e7-8583-2c980de1790e.png">

**Comment by chaoguodeng** [comment]
@chengxulvtu 需要经过多个区块的确认后，挖矿奖励才可以用。请点击“”详情“”查看细节。
