### ISSUE TITLE
今天去看了看EOS的代码库，回头来看看我们曾经的信仰

### ISSUE THREAD

**Issue by tiaotiao00** [HcashOrg/hcashd#30]
我们曾经相信团队可以做事可是现在看到的是团队碌碌无为，还在哪里说社区贡献人数少，那你们为什么众筹呢，众筹给你的篇是干嘛的呢？是让你们做开发，做社区维护是为我们的信仰去服务的。到现在你们敢公开社区当时众筹资金的开支证明吗？敢胖社区投票律师事务所监督嘛？敢胖他们做一次审查吗？？说了这么多你敢做那一件事？我失望了我放弃了

**Comment by keyboard1989** [comment]
这就是割韭菜的一个项目，trx代码库更新的也比这强，欺负别人啥都不懂，我看了大部分的hcash的项目，只有第一次提交是把别人的代码拷贝过来，改吧改吧，然后后面的都是add debug code 或者 delete debug code，我已经不想说什么骂人的脏话了。我也失望了放弃了
