### ISSUE TITLE
wiki有误

### ISSUE THREAD

**Issue by Goya-** [HcashOrg/hcashd#5]
`hcashctl`后面少了个空格..
![chrome_2017-12-19_13-06-40](https://user-images.githubusercontent.com/7187511/34141638-7881f2b4-e4bd-11e7-9a28-9b3005162f3c.png)

https://github.com/HcashOrg/hcashd/wiki/HcashWallet-GUI%E4%B8%BB%E9%93%BE%E6%B5%8B%E8%AF%95%E7%89%88%E6%9C%AC%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

**Comment by chaoguodeng** [comment]
@Goya- 非常感谢提醒，已经修正
